[package]
name = "successors_vs_iterate"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
itertools = "0.14.0"

[lints.rust]
unsafe_code = "forbid"
dead_code = "allow"

[lints.clippy]
# allow-unwrap-in-tests = true
unwrap_used = { level = "deny", priority = 1 }
many_single_char_names = { level = "allow", priority = 1 }
pedantic = { level = "warn", priority = 0 }
# nursery = { level = "warn", priority = 0 }
all = { level = "warn", priority = -1 }
